name: taidam_tutor
description: "A Flutter application for learning Tai Dam language."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  sqflite:
  just_audio: ^0.10.2
  audioplayers: ^6.4.0
  shared_preferences: ^2.3.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/data/
    - assets/images/svg/
    - assets/images/png/

  fonts:
    - family: Tai Heritage Pro
      fonts:
        - asset: assets/fonts/TaiHeritagePro-B.ttf
        - asset: assets/fonts/TaiHeritagePro-R.ttf
    - family: Tai Heritage
      fonts:
        - asset: assets/fonts/taiherr.ttf
